### ISSUE TITLE
2141bis: Section 3.2 Namespace specific string syntax

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#1]
From John:

> Section 3.2 Namespace specific string syntax, doesn't seem
> completely clear when p-, q-, or f-components are possible, nor
> is it clear about any syntax issues within those components.  
> 
> Anyone have opinions about what should be said, or do Peter and
> I need to take a guess at this?    If you do have opinions, text
> would be ideal along with explanation/ justification.

**Comment by klensin** [comment]
2015-01-21: Still open but maybe partially OBE given other issues..   See http://www.ietf.org/mail-archive/web/urn/current/msg02724.html

**Comment by MelindaShore** [comment]
We believe that this is settled, but it may be reopened depending on feedback on the -12 draft.
