### ISSUE TITLE
2141bis: Backward compatibility

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#10]
> The registration procedures for formal and informal namespaces
> (Sections 8.1 and 8.2) both provide for revisions of the
> registration by updating the template.   Especially given some
> discussions in the WG, I think we should impose an explicit
> requirement for a description of differences from prior versions
> and/or backward compatibility in updated registrations.
> 
> Do others agree?

**Comment by klensin** [comment]
There have been a few comments and suggestions about this on the mailing list.  Text in -10 assumes that it has been resolved in favor of a MUST requirement.

**Comment by MelindaShore** [comment]
Fixed in -10.
