### ISSUE TITLE
2141bis: IANA considerations and Interoperability

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#11]
From John:

> Under IANA Considerations - URI Scheme, Section 10.1, the text
> says
> 
> ```
>   "Interoperability Considerations:  There are no known
>   interoperability concerns related to use of the 'urn'
>   URI scheme."
> ```
> 
> IMO, this is not strictly true because the whole discussion of
> whether URNs can be (or should be, or are meaningful in) various
> contexts and/or in relative URI form is ultimately about
> interoperability considerations.  One could argue that almost
> everything else that RFC 3986 considers a per-scheme issue and
> that we have made per-NID for URNs falls into the same category.
> 
> Should more be said in that line item and, if so, what?

**Comment by MelindaShore** [comment]
query sent to mailing list on 1/12

**Comment by MelindaShore** [comment]
Needs more text.  From Juha: 

> Instead of just saying that there are no known interoperability concerns, we could admit that some 
> namespaces (but not all) may have them in the future, and add to the existing text something like this:
> "If interoperability concerns arise during the registration of a URN namespace due to e.g. syntax or 
>  scope of an identifier system, they should be resolved in the namespace registration request."
> 
> Since we do not know either what kind of identifier systems will have URN namespaces in the future, 
> or what kind of technical infrastructure they will rely on (in the distant future), there is no way to |
> produce an exhaustive list of concerns in 2141bis. Rather than trying it is better to offload this 
> responsibility to the registrants.

**Comment by klensin** [comment]
See Section 7.3.5 of 2141bis-11 and further text along the lines above in Section 7.3.5 of -12
