### ISSUE TITLE
Consolidate 2141bis and "semantics" drafts

### ISSUE THREAD

**Issue by klensin** [MelindaShore/urnbis#12]
Ted Hardie (and maybe others) have suggested that we should fold the "3956 syntax only" draft ((draft-ietf-urnbis-semantics-clarif) into draft-ietf-urnbis-rfc2141bis-urn.  

Pro: There is material in the former draft that has been needed for WG discussions but it not needed long-term (i.e., in an RFC) and consolidating the two would reduce the potential for confusion..

Con: Could further delay getting the work of the WG finished.  Making this sort of consolidation and removing unneeded material in the process carries a high risk of errors unless there is very careful review by the WG.

**Comment by klensin** [comment]
We seem to have tentatively concluded that the risks associated with trying to do this now, when documents are in transition, are just too high.

**Comment by MelindaShore** [comment]
Won't fix.
