### ISSUE TITLE
2141bis: Section 4.1 "normalization" comment

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#3]
> Section 4.1 ("Procedure"), third paragraph, talks about
> "applying case normalization".  There is no such thing in
> Unicode even though 3986 has a section of that title .   It
> would be an editorial issue and easily fixed if I was sure what
> the WG intended, but I'm not.  It isn't clear whether Section
> 6.2.2.1 of RFC 3986 is included or excluded by a "syntax only"
> policy.  Even if it is included, it generically applies to the
> two characters that follow "%" in percent-encoding, the scheme
> name, and the host (the latter being irrelevant for URNs).
> Other components are specified on a per-scheme basis.
> 
> Independent of the terminology it uses, the text in 3986
> specifies that the characters that follow "%" in
> percent-encoding must be converted to upper case and that scheme
> names (and the host component) must be converted to lower case.
> The text in the current version of 2141bis says (construct 4)
> that the p-component is to have "case normalization" applied,
> but doesn't specify upper case, lower case, or case folding.
> We either need to get p-components out of that list, making them
> case-sensitive, or need to choose one of the three.   Note that,
> because of situations like "what happens with accent marks when
> converting to upper case" (and its opposite of an accent-free
> upper case character potentially mapping to two or more lower
> case characters), arguments that position-dependent characters
> in Arabic or other scripts should really be treated as case
> variations, etc., this is not a trivial decision.  If we care
> about consistency with the reasoning of IDNA and probably
> PRECIS, we should probably (but only probably) preserve
> case-sensitivity as much as possible.

**Comment by klensin** [comment]
2015-01-21" Peter indicated a desire to think about this further.  I've inserted a placeholder and some additional comments into -09c.  See http://www.ietf.org/mail-archive/web/urn/current/msg02726.html

I believe that Mark Davis's comment at http://www.ietf.org/mail-archive/web/urn/current/msg02727.html, while interesting and possibly controversial, is completely irrelevant to this particular discussion except insofar as it, again, shows an instance of "there are lots of exception cases but they are ok as long as you understand the language and/or locale context".... except that we can't count on that (this is the Unicode 7.0 Hamza Above issue in another disguise).

**Comment by klensin** [comment]
This has been re-tuned in Section 4 of 2141bis-11.  I think we are finished with it unless there are further comments on the list.
