### ISSUE TITLE
2141bis: Section 5 on URI Conformance

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#4]
From John: 

> We've had some on-list discussion about the wording of parts of
> Section 5 of 2141bis.  I think we've reached general agreement
> about some of the language in the first paragraph or two and
> Peter or I will post draft text sometime soon to see if it is
> actually what the WG intends.   
> 
> However, a careful reading of the rest of that section turns up
> several related issues.   Before trying to write and circulate
> draft text, I want to verify that it is the view of the URN WG
> that precise rules (and constraints and restrictions) for the
> use of URNs embedded in various contexts is the job of the
> definitions for those contexts, not 2141bis or other generic URN
> documents.
> 
> On particular, while 2141bis can (and probably should) offer
> general guidance for issues a context/usage designer should
> think about, decisions about what can, or cannot, appear with
> href in <a> elements are a matter for HTML, not this
> specification.
> 
> Is the WG in enough agreement about that to allow us to draft
> text?

**Comment by klensin** [comment]
2015-01-21: At least Peter and I are in agreement.  I've drafted text (which also appears in -09c and -09c) and sent it to the list.   If that text is greeted with silence, I think this item can be closed out.   See http://www.ietf.org/mail-archive/web/urn/current/msg02728.html

**Comment by klensin** [comment]
Text incorporated in -09 and -10 of the I-D.
