### ISSUE TITLE
2141bis: Section 6 and valid and invalid URNs

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#5]
From John:

> Section 6 ("URN Namespaces") of 2141bis talks about valid and
> invalid, formal and informal URNs.  The combinations are a
> little confusing, especially since the current text makes a
> string that generally follows the URN syntax but that uses an
> unregistered NID invalid.  I think some clarification is in
> order and want to make sure the WG agrees.  Hence:
> 
> Question 1: It is our intent to keep URN-like objects based on
> unregistered namespace invalid, right?
> 
> Question 2: The last paragraph of the Section 6 introduction
> (before Section 6.1 starts) disposes of "experimental"
> namespaces.  I believe it should be made clear that continued
> use of such namespaces with URN-like syntax does not make them
> valid URNs (because they are unregistered).   If anyone
> disagrees, please speak up not.

**Comment by klensin** [comment]
2015-01-21: Based on the (as usual, very limited) list discussion, this should probably be closed out.  I've inserted draft text in -09c to clarify that experimental URNs are invalid because they are not registered.   See http://www.ietf.org/mail-archive/web/urn/current/msg02729.html

**Comment by klensin** [comment]
Text incorporated in 2141bis-09 (and preserved in -10 and -11) that reflects the above.
