### ISSUE TITLE
2141bis: Equivalence rules

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#8]
From John:

> In Section 7.2, item 3, there is a sentence that reads:
> 
> ```
>   If it is appropriate and helpful, reference can be made
>   to the equivalence rules defined in the URI
>   specification [RFC3986].
> ```
> 
> Given all of the controversy we have had about those rules and
> what is required, suggested, ordered or unordered, etc., I
> suggest the above is looking for trouble.  How would people feel
> about
> 
> ```
>   "... reference can be made to specific equivalence rules
>   defined..."
> ```
> 
> as a way to get around that without making a big deal of it?

**Comment by klensin** [comment]
in -10 of the I-D, I have assumed that silence indicates consent and made this change.
