### ISSUE TITLE
2141bis: Expert review

### ISSUE THREAD

**Issue by MelindaShore** [MelindaShore/urnbis#9]
From John:

> Section 8 of the document, on registration of namespaces,
> specifies Expert Review and points to RFC 5226.  The expert
> review provisions there are fairly specific.
> draft-leiba-cotton-iana-5226bis-11 is better, but still doesn't
> align with the discussion I think we had many months ago about
> creating a committee (not just a set of rotating individuals to
> spread the load) and about being very specific that the "expert"
> role was one of advising and trying to convince people to
> produce better-quality registration specs, not accepting or
> rejecting registrations.
> 
> If my memory of that is correct, this section will need some
> work and text suggestions would be welcome.
> 
> Is  my memory correct or do we need to discuss those issues
> further?

**Comment by MelindaShore** [comment]
From John:

> Sorry... didn't read my notes carefully enough.
> 
> I should have added that Section 9 does discuss some of the
> issue and should be pointed to in, or merged with, the first
> paragraph of Section 8.1 (an editorial matter), but Section 9
> still somewhat contradicts the language of RFC 2226.

**Comment by klensin** [comment]
Explicit placeholder/question about this added in -10.  See also 2015-03-04 message to mailing list, http://www.ietf.org/mail-archive/web/urn/current/msg02786.html

**Comment by klensin** [comment]
Text reflecting the above incorporated into 2141bis-11.  May (or may not) need further improvement to avoid over-formalizing "report" -- text welcome.

**Comment by MelindaShore** [comment]
Text incorporated
